[build]
builder = "NIXPACKS"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
numReplicas = 1
startCommand = "./out serve --http=0.0.0.0:8090 --dir=/data/pb_data"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10